create type public.question_status as enum ('pending', 'recovering', 'resolved');

create table public.questions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles (id) on delete cascade,
  image_url text not null check (length(btrim(image_url)) > 0),
  raw_text text,
  status public.question_status not null default 'pending',
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table public.recovery_missions (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions (id) on delete cascade,
  steps jsonb not null,
  current_step integer not null default 0 check (current_step >= 0),
  is_completed boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint recovery_missions_steps_array_check check (jsonb_typeof(steps) = 'array')
);

comment on table public.questions is 'Wrong-answer question captured by a student.';
comment on column public.questions.image_url is 'Public or signed storage URL for the captured question image.';
comment on column public.questions.raw_text is 'Problem text extracted from vision/OCR analysis.';
comment on table public.recovery_missions is 'Three-step recovery mission generated for a question.';
comment on column public.recovery_missions.steps is 'Structured step hints generated by the AI service.';

create index questions_student_id_created_at_idx on public.questions (student_id, created_at desc);
create index recovery_missions_question_id_idx on public.recovery_missions (question_id);

grant usage on type public.question_status to authenticated, service_role;
grant select, insert, update on public.questions to authenticated;
grant select, insert, update on public.recovery_missions to authenticated;
grant all on public.questions to service_role;
grant all on public.recovery_missions to service_role;

alter table public.questions enable row level security;
alter table public.recovery_missions enable row level security;

create policy "Students can read own questions"
  on public.questions
  for select
  to authenticated
  using (student_id = auth.uid());

create policy "Students can insert own questions"
  on public.questions
  for insert
  to authenticated
  with check (student_id = auth.uid());

create policy "Students can update own questions"
  on public.questions
  for update
  to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

create policy "Students can read own recovery missions"
  on public.recovery_missions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.questions
      where questions.id = recovery_missions.question_id
        and questions.student_id = auth.uid()
    )
  );

create policy "Students can insert own recovery missions"
  on public.recovery_missions
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.questions
      where questions.id = recovery_missions.question_id
        and questions.student_id = auth.uid()
    )
  );

create policy "Students can update own recovery missions"
  on public.recovery_missions
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.questions
      where questions.id = recovery_missions.question_id
        and questions.student_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.questions
      where questions.id = recovery_missions.question_id
        and questions.student_id = auth.uid()
    )
  );
